### ISSUE TITLE
publish wasmtime v13.0.0 to npm

### ISSUE THREAD

**Issue by cataggar** [ctaggart/npm-wasmtime-cli#1]
Publish the x86_64 builds from
https://github.com/bytecodealliance/wasmtime/releases/tag/v13.0.0

https://www.npmjs.com/package/@cataggar/wasmtime-cli-linux
https://www.npmjs.com/package/@cataggar/wasmtime-cli-macos
https://www.npmjs.com/package/@cataggar/wasmtime-cli-windows

To use:
npm -g i @cataggar/wasmtime-cli-linux
npm -g i @cataggar/wasmtime-cli-macos
npm -g i @cataggar/wasmtime-cli-windows

**Comment by ctaggart** [comment]
Requested official packages at https://github.com/bytecodealliance/wasmtime/issues/7192
